main: com.cavetale.afk.AFKPlugin
name: AFK

version: 0.1
api-version: '1.21.8'

description: Player AFK detection
author: StarTux
website: https://cavetale.com

depend: [Core, Title, Chat]
softdepend: []

commands:

  afk:
    aliases: []
    description: Enter afk state
    usage: /afk - Toggle afk
    permission: afk.afk

  afkadmin:
    aliases: []
    description: Admin command
    usage: /afkadmin
    permission: afk.admin

permissions:

  afk.afk:
    description: Use /afk
    default: op

  afk.admin:
    description: Use /afkadmin
    default: op

  afk.nokick:
    description: Never get kicked
    default: op

  afk.longkick:
    description: Kick after long time
    default: false