main: com.cavetale.afk.AFKPlugin

name: AFK
version: 0.1
api-version: 1.13

description: Player AFK detection
author: StarTux
website: https://cavetale.com

depend: [Title]
softdepend: []

commands:
  afk:
    aliases: []
    description: Enter afk state
    usage: |-
      /afk - Toggle afk
      /afk info <player> - Get info on player
      /afk list - List afk players
    permission: afk.afk

permissions:
  afk.afk:
    description: Use /afk
    default: op

  afk.nokick:
    description: Never get kicked
    default: op