main: com.cavetale.afk.AFKPlugin

name: AFK
version: 0.1
api-version: 1.13

description: Player AFK detection
author: StarTux
website: https://cavetale.com

depend: []
softdepend: []

permissions:
  afk:
    aliases: []
    description: Enter afk state
    usage: /afk
    permission: afk.afk

permissions:
  afk.afk:
    description: Use /afk
    default: op
